### ISSUE TITLE
Investigate the *valley of death* problem

### ISSUE THREAD

**Issue by bhiriyur** [WillBux/Crash-Course-CarND-Capstone#7]
I was able to replicate the 'valley of death' problem where the car veers off the track and stops. It only resumes when the camera is turned off. This issue is related to identifying the cause and finding a solution to this problem (does turning off ros logs help at all?). Alternatively a decision can be made as to whether this is a problem with the simulator, in which case, we can ignore this problem.

**Comment by fspirit** [comment]
It could be internal sim problem, will try to get help on slack
